#!/usr/bin/env python3
"""Comfy Assistant Builder - local workflow assistant and Chrome bridge."""

from __future__ import annotations

import json
import mimetypes
import os
import re
import secrets
import struct
import sys
import time
import webbrowser
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib import request as urlrequest
from urllib.error import URLError
from urllib.parse import parse_qs, urlparse


APP_DIR = Path(__file__).resolve().parent
STATIC_DIR = APP_DIR / "static"
TEMPLATE_DIR = APP_DIR / "templates"
EXTENSION_CONFIG = APP_DIR / "chrome_extension" / "cab_config.js"
COMFY_ROOT = Path(os.environ.get("CAB_COMFY_ROOT", str(Path.home() / "Documents/ComfyUI"))).expanduser()
COMFY_WORKFLOWS = COMFY_ROOT / "user/default/workflows"
MODELS_ROOT = COMFY_ROOT / "models"
DESKTOP_WORKFLOWS = Path(os.environ.get("CAB_WORKFLOWS_DIR", str(Path.home() / "Desktop/workflows"))).expanduser()
HOST = os.environ.get("CAB_HOST", "127.0.0.1")
PORT = int(os.environ.get("CAB_PORT", "8797"))
COMFY_API = os.environ.get("CAB_COMFY_API", "http://127.0.0.1:8188").rstrip("/")
TOKEN_PATH = Path(os.environ.get("CAB_TOKEN_PATH", str(APP_DIR / ".cab_token"))).expanduser()


MODEL_DIRS = {
    "checkpoints": MODELS_ROOT / "checkpoints",
    "diffusion_models": MODELS_ROOT / "diffusion_models",
    "loras": MODELS_ROOT / "loras",
    "text_encoders": MODELS_ROOT / "text_encoders",
    "vae": MODELS_ROOT / "vae",
}


def load_token():
    if TOKEN_PATH.exists():
        return TOKEN_PATH.read_text(encoding="utf-8").strip()
    token = secrets.token_urlsafe(32)
    TOKEN_PATH.write_text(token + "\n", encoding="utf-8")
    try:
        TOKEN_PATH.chmod(0o600)
    except OSError:
        pass
    return token


API_TOKEN = load_token()


def write_extension_config():
    raw = (
        "// Generated by Comfy Assistant Builder. Do not commit personal tokens.\n"
        f"window.CAB_SERVER = {json.dumps(f'http://{HOST}:{PORT}')};\n"
        f"window.CAB_EXTENSION_TOKEN = {json.dumps(API_TOKEN)};\n"
    )
    try:
        EXTENSION_CONFIG.write_text(raw, encoding="utf-8")
    except OSError as exc:
        print(f"Warning: could not write Chrome extension config: {exc}", file=sys.stderr)


def slugify(text: str) -> str:
    text = text.strip() or "workflow"
    text = re.sub(r"[^A-Za-z0-9._ -]+", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text[:90] or "workflow"


def list_files(root: Path, suffixes=(".safetensors", ".ckpt", ".pt", ".pth", ".bin")):
    if not root.exists():
        return []
    out = []
    for path in root.rglob("*"):
        if path.is_file() and path.suffix.lower() in suffixes:
            out.append(str(path.relative_to(root)))
    return sorted(out, key=str.lower)


def scan_models():
    data = {name: list_files(path) for name, path in MODEL_DIRS.items()}
    data["lora_catalog"] = lora_catalog(data["loras"])
    data["workflow_root"] = str(DESKTOP_WORKFLOWS)
    data["comfy_workflows"] = str(COMFY_WORKFLOWS)
    data["recipes"] = [
        {
            "id": "flux_lora",
            "title": "Flux image with one LoRA",
            "media_type": "image",
            "family": "Flux",
            "description": "Flux.1 dev, one model-only LoRA loader, empty negative, 1024 square output.",
        },
        {
            "id": "flux_base",
            "title": "Flux base image",
            "media_type": "image",
            "family": "Flux",
            "description": "Flux.1 dev without LoRA for clean prompt tests.",
        },
        {
            "id": "wan_t2v",
            "title": "Wan 2.2 text-to-video",
            "media_type": "video",
            "family": "Wan",
            "description": "Wan high-noise to low-noise text-to-video starter workflow.",
        },
        {
            "id": "ltxv_t2v",
            "title": "LTXV text-to-video",
            "media_type": "video",
            "family": "LTXV",
            "description": "LTXV distilled text-to-video starter.",
        },
    ]
    return data


def recipe_family(recipe: str) -> str:
    if recipe in {"flux_lora", "flux_base"}:
        return "Flux"
    if recipe == "wan_t2v":
        return "Wan"
    if recipe == "ltxv_t2v":
        return "LTXV"
    return "Unknown"


def lora_path(name: str) -> Path:
    root = MODEL_DIRS["loras"].resolve()
    path = (root / str(name or "")).resolve()
    if root != path and root not in path.parents:
        raise ValueError("LoRA path is outside the allowed folder")
    if not path.exists() or not path.is_file():
        raise FileNotFoundError("LoRA was not found")
    return path


def read_safetensors_metadata(path: Path):
    if path.suffix.lower() != ".safetensors":
        return {}
    with path.open("rb") as fh:
        raw_len = fh.read(8)
        if len(raw_len) != 8:
            return {}
        header_len = struct.unpack("<Q", raw_len)[0]
        if header_len <= 0 or header_len > 50_000_000:
            return {}
        header = json.loads(fh.read(header_len).decode("utf-8"))
    return header.get("__metadata__", {}) or {}


def flatten_trigger_value(value):
    if value is None:
        return []
    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()]
    if isinstance(value, dict):
        out = []
        for key, item in value.items():
            if isinstance(item, (int, float)) and item <= 0:
                continue
            out.append(str(key).strip())
        return [item for item in out if item]
    text = str(value).strip()
    if not text:
        return []
    try:
        parsed = json.loads(text)
    except Exception:
        parsed = None
    if parsed is not None and parsed is not value:
        return flatten_trigger_value(parsed)
    return [part.strip() for part in re.split(r"[,;\n]+", text) if part.strip()]


def extract_trigger_words(metadata):
    direct_keys = [
        "trigger_words",
        "trigger_word",
        "trained_words",
        "trainedWords",
        "activation text",
        "activation_text",
        "trigger_phrase",
        "modelspec.trigger_phrase",
        "ss_trigger_words",
    ]
    triggers = []
    sources = []
    for key in direct_keys:
        if key in metadata:
            values = flatten_trigger_value(metadata.get(key))
            if values:
                triggers.extend(values)
                sources.append(key)
    if not triggers and metadata.get("ss_tag_frequency"):
        values = flatten_trigger_value(metadata.get("ss_tag_frequency"))
        if values:
            triggers.extend(values[:12])
            sources.append("ss_tag_frequency")
    clean = []
    seen = set()
    for item in triggers:
        item = re.sub(r"\s+", " ", item).strip()
        item = re.sub(r"^\d+[_: -]+", "", item).strip()
        if not item:
            continue
        low = item.lower()
        if low in seen:
            continue
        seen.add(low)
        clean.append(item)
    return clean[:24], sources


def classify_lora(name: str, metadata=None):
    metadata = metadata or {}
    text = " ".join(
        [
            name,
            str(metadata.get("modelspec.architecture", "")),
            str(metadata.get("modelspec.implementation", "")),
            str(metadata.get("modelspec.title", "")),
            str(metadata.get("ss_base_model_version", "")),
            str(metadata.get("ss_sd_model_name", "")),
            str(metadata.get("ss_network_module", "")),
            str(metadata.get("ss_output_name", "")),
        ]
    ).lower()
    if "flux" in text:
        return "Flux"
    if "wan" in text:
        return "Wan"
    if "ltxv" in text or "ltx-video" in text or "pytorch_lora_weights" in text:
        return "LTXV"
    if "sdxl" in text or "xl" in text or "stable-diffusion-xl" in text:
        return "SDXL"
    if "sd1.5" in text or "sd15" in text or "stable-diffusion-v1" in text or "v1-5" in text:
        return "SD1.5"
    if "qwen" in text:
        return "Qwen"
    return "Unknown"


def lora_catalog(loras=None):
    root = MODEL_DIRS["loras"].resolve()
    out = []
    for name in loras if loras is not None else list_files(MODEL_DIRS["loras"]):
        try:
            path = lora_path(name)
            metadata = read_safetensors_metadata(path)
            triggers, sources = extract_trigger_words(metadata)
            family = classify_lora(name, metadata)
            out.append(
                {
                    "name": str(path.relative_to(root)),
                    "family": family,
                    "compatible_recipes": compatible_recipes_for_family(family),
                    "trigger_words": triggers,
                    "source_keys": sources,
                    "has_metadata": bool(metadata),
                }
            )
        except Exception as exc:
            out.append(
                {
                    "name": str(name),
                    "family": "Unreadable",
                    "compatible_recipes": [],
                    "trigger_words": [],
                    "source_keys": [],
                    "has_metadata": False,
                    "error": str(exc),
                }
            )
    return sorted(out, key=lambda item: (item["family"], item["name"].lower()))


def compatible_recipes_for_family(family: str):
    return {
        "Flux": ["flux_lora"],
        "Wan": ["wan_t2v"],
        "LTXV": ["ltxv_t2v"],
    }.get(family, [])


def lora_info(name: str):
    path = lora_path(name)
    metadata = read_safetensors_metadata(path)
    triggers, sources = extract_trigger_words(metadata)
    root = MODEL_DIRS["loras"].resolve()
    return {
        "ok": True,
        "name": str(path.relative_to(root)),
        "family": classify_lora(str(path.relative_to(root)), metadata),
        "compatible_recipes": compatible_recipes_for_family(classify_lora(str(path.relative_to(root)), metadata)),
        "trigger_words": triggers,
        "source_keys": sources,
        "metadata_keys": sorted(metadata.keys())[:80],
        "has_metadata": bool(metadata),
    }


def pick(items, contains, fallback=None):
    contains = [c.lower() for c in contains]
    for item in items:
        low = item.lower()
        if all(c in low for c in contains):
            return item
    return fallback or (items[0] if items else "")


def infer_recipe(text: str) -> str:
    low = text.lower()
    if "wan" in low or "video" in low:
        return "wan_t2v"
    if "ltx" in low:
        return "ltxv_t2v"
    if "no lora" in low or "base" in low:
        return "flux_base"
    return "flux_lora"


def normalize_media_type(value: str, recipe: str) -> str:
    text = str(value or "").strip().lower()
    if text in {"image", "video"}:
        return text
    return "video" if recipe in {"wan_t2v", "ltxv_t2v"} else "image"


def best_lora_for_prompt(prompt: str, loras):
    low = prompt.lower()
    priority = []
    if "kwingo" in low or "wingo" in low:
        priority.append("kwingo")
    if "tracy" in low:
        priority.append("tracy_flux.1-dev_r16_final")
    if "real" in low:
        priority.append("flux_realism")
    priority.extend(["kwingo", "tracy_flux.1-dev_r16_final", "flux_realism", "flux-lora"])
    for token in priority:
        for lora in loras:
            if token in lora.lower():
                return lora
    return loras[0] if loras else ""


def node(
    nid,
    ntype,
    pos,
    size,
    order,
    inputs=None,
    outputs=None,
    widgets=None,
    title=None,
    properties=None,
    color=None,
    bgcolor=None,
):
    out = {
        "id": nid,
        "type": ntype,
        "pos": pos,
        "size": size,
        "flags": {},
        "order": order,
        "mode": 0,
        "inputs": inputs or [],
        "outputs": outputs or [],
        "properties": properties if properties is not None else {"Node name for S&R": ntype},
    }
    if widgets is not None:
        out["widgets_values"] = widgets
    if title:
        out["title"] = title
    if color:
        out["color"] = color
    if bgcolor:
        out["bgcolor"] = bgcolor
    return out


def out_slot(name, typ, links):
    return {"name": name, "type": typ, "slot_index": 0, "links": links}


def in_slot(name, typ, link):
    return {"name": name, "type": typ, "link": link}


def ensure_lora_compatible(name: str, recipe: str):
    info = lora_info(name)
    if recipe not in info["compatible_recipes"]:
        family = info.get("family", "Unknown")
        expected = recipe_family(recipe)
        raise ValueError(f"{name} is tagged as {family}, not compatible with the {expected} recipe")
    return info


def normalize_lora_slots(prompt, payload_loras, fallback_lora=None, fallback_strength=0.75, recipe="flux_lora"):
    slots = []
    if isinstance(payload_loras, list):
        for item in payload_loras:
            if not isinstance(item, dict):
                continue
            name = str(item.get("name") or "").strip()
            if not name:
                continue
            try:
                strength = float(item.get("strength", fallback_strength))
            except (TypeError, ValueError):
                strength = fallback_strength
            ensure_lora_compatible(name, recipe)
            slots.append({"name": name, "strength": strength})
    elif fallback_lora:
        ensure_lora_compatible(fallback_lora, recipe)
        slots.append({"name": fallback_lora, "strength": float(fallback_strength)})
    return slots[:5]


def auto_lora_slots(prompt, recipe="flux_lora", fallback_strength=0.75):
    models = scan_models()
    slots = []
    if not slots:
        compatible = [
            item["name"]
            for item in models.get("lora_catalog", [])
            if recipe in item.get("compatible_recipes", [])
        ]
        best = best_lora_for_prompt(prompt, compatible)
        if best:
            slots.append({"name": best, "strength": float(fallback_strength)})
    return slots[:5]


def flux_workflow(
    prompt,
    *,
    lora=None,
    loras=None,
    strength=0.75,
    with_lora=True,
    title="Flux Assistant Workflow",
    quality="balanced",
):
    models = scan_models()
    unet = pick(models["diffusion_models"], ["flux1-dev"], "flux1-dev.safetensors")
    clip_l = pick(models["text_encoders"], ["clip_l"], "clip_l.safetensors")
    t5 = pick(models["text_encoders"], ["t5xxl", "fp16"], "t5xxl_fp16.safetensors")
    vae = pick(models["vae"], ["ae"], "ae.safetensors")
    lora_slots = normalize_lora_slots(prompt, loras, lora, strength, recipe="flux_lora") if with_lora else []
    profile = quality_profile(quality)
    positive = prompt.strip() or "photorealistic portrait, natural light, detailed eyes"
    if any("kwingo" in slot["name"].lower() for slot in lora_slots) and "wingo woman" not in positive.lower():
        positive = f"wingo woman, {positive}"

    nodes = []
    links = []
    last_model_link = 101
    last_model_node = 1
    next_id = 2
    next_link = 102

    nodes.append(
        node(
            1,
            "UNETLoader",
            [40, 40],
            [315, 110],
            0,
            outputs=[out_slot("MODEL", "MODEL", [101])],
            widgets=[unet, "default"],
            properties={
                "Node name for S&R": "UNETLoader",
                "models": [{"name": unet, "directory": "diffusion_models"}],
            },
        )
    )

    for index, slot in enumerate(lora_slots, start=1):
        node_id = next_id
        out_link_id = next_link
        nodes.append(
            node(
                node_id,
                "LoraLoaderModelOnly",
                [400 + ((index - 1) * 390), 40],
                [360, 82],
                index,
                inputs=[in_slot("model", "MODEL", last_model_link)],
                outputs=[out_slot("MODEL", "MODEL", [out_link_id])],
                widgets=[slot["name"], float(slot["strength"])],
                title=f"LoRA {index}",
            )
        )
        links.append([last_model_link, last_model_node, 0, node_id, 0, "MODEL"])
        last_model_link = out_link_id
        last_model_node = node_id
        next_id += 1
        next_link += 1

    clip_id = next_id
    prompt_id = next_id + 1
    neg_id = next_id + 2
    latent_id = next_id + 3
    sampler_id = next_id + 4
    vae_id = next_id + 5
    decode_id = next_id + 6
    save_id = next_id + 7
    note_id = next_id + 8
    clip_link = next_link
    positive_link = next_link + 1
    negative_source_link = next_link + 2
    negative_link = next_link + 3
    latent_link = next_link + 4
    sampled_link = next_link + 5
    vae_link = next_link + 6
    image_link = next_link + 7

    nodes.extend(
        [
            node(
                clip_id,
                "DualCLIPLoader",
                [40, 210],
                [315, 180],
                next_id,
                outputs=[out_slot("CLIP", "CLIP", [clip_link])],
                widgets=[clip_l, t5, "flux", "default"],
                properties={
                    "Node name for S&R": "DualCLIPLoader",
                    "models": [
                        {"name": clip_l, "directory": "text_encoders"},
                        {"name": t5, "directory": "text_encoders"},
                    ],
                },
            ),
            node(
                prompt_id,
                "CLIPTextEncode",
                [400, 210],
                [560, 180],
                next_id + 1,
                inputs=[in_slot("clip", "CLIP", clip_link)],
                outputs=[out_slot("CONDITIONING", "CONDITIONING", [positive_link, negative_source_link])],
                widgets=[positive],
                title="Positive Prompt",
                color="#232",
                bgcolor="#353",
            ),
            node(
                neg_id,
                "ConditioningZeroOut",
                [1000, 270],
                [230, 80],
                next_id + 2,
                inputs=[in_slot("conditioning", "CONDITIONING", negative_source_link)],
                outputs=[out_slot("CONDITIONING", "CONDITIONING", [negative_link])],
                title="Flux Empty Negative",
            ),
            node(
                latent_id,
                "EmptySD3LatentImage",
                [40, 460],
                [315, 170],
                next_id + 3,
                outputs=[out_slot("LATENT", "LATENT", [latent_link])],
                widgets=[1024, 1024, 1],
            ),
            node(
                sampler_id,
                "KSampler",
                [1280, 210],
                [320, 350],
                next_id + 4,
                inputs=[
                    in_slot("model", "MODEL", last_model_link),
                    in_slot("positive", "CONDITIONING", positive_link),
                    in_slot("negative", "CONDITIONING", negative_link),
                    in_slot("latent_image", "LATENT", latent_link),
                ],
                outputs=[out_slot("LATENT", "LATENT", [sampled_link])],
                widgets=[0, "randomize", profile["flux_steps"], 1, "euler", "simple", 1],
            ),
            node(
                vae_id,
                "VAELoader",
                [400, 460],
                [315, 110],
                next_id + 5,
                outputs=[out_slot("VAE", "VAE", [vae_link])],
                widgets=[vae],
                properties={
                    "Node name for S&R": "VAELoader",
                    "models": [{"name": vae, "directory": "vae"}],
                },
            ),
            node(
                decode_id,
                "VAEDecode",
                [1650, 250],
                [230, 100],
                next_id + 6,
                inputs=[in_slot("samples", "LATENT", sampled_link), in_slot("vae", "VAE", vae_link)],
                outputs=[out_slot("IMAGE", "IMAGE", [image_link])],
            ),
            node(
                save_id,
                "SaveImage",
                [1920, 210],
                [315, 270],
                next_id + 7,
                inputs=[in_slot("images", "IMAGE", image_link)],
                widgets=["Assistant_Flux"],
            ),
            node(
                note_id,
                "Note",
                [760, 460],
                [500, 170],
                next_id + 8,
                widgets=[
                    "Generated by Comfy Assistant Builder. LoRA nodes are chained in order. Start character LoRAs around 0.6-0.8 and style/detail LoRAs lower, then tune strength."
                    if with_lora
                    else "Generated by Comfy Assistant Builder. Base Flux workflow with no LoRA."
                ],
                properties={},
                color="#432",
                bgcolor="#000",
            ),
        ]
    )
    links.append([last_model_link, last_model_node, 0, sampler_id, 0, "MODEL"])
    links.extend(
        [
            [clip_link, clip_id, 0, prompt_id, 0, "CLIP"],
            [positive_link, prompt_id, 0, sampler_id, 1, "CONDITIONING"],
            [negative_source_link, prompt_id, 0, neg_id, 0, "CONDITIONING"],
            [negative_link, neg_id, 0, sampler_id, 2, "CONDITIONING"],
            [latent_link, latent_id, 0, sampler_id, 3, "LATENT"],
            [sampled_link, sampler_id, 0, decode_id, 0, "LATENT"],
            [vae_link, vae_id, 0, decode_id, 1, "VAE"],
            [image_link, decode_id, 0, save_id, 0, "IMAGE"],
        ]
    )
    return workflow(title, nodes, links, note_id, image_link, family="Flux")


QUALITY_PROFILES = {
    "draft": {
        "flux_steps": 24,
        "wan_steps": 12,
        "wan_split": 6,
        "wan_cfg": 3.0,
        "wan_width": 640,
        "wan_height": 640,
        "wan_fps": 16,
        "wan_duration": 4,
        "ltxv_steps": 24,
        "ltxv_cfg": 3.0,
        "ltxv_width": 768,
        "ltxv_height": 512,
        "ltxv_frames": 73,
        "ltxv_fps": 24,
    },
    "balanced": {
        "flux_steps": 32,
        "wan_steps": 20,
        "wan_split": 10,
        "wan_cfg": 3.5,
        "wan_width": 640,
        "wan_height": 640,
        "wan_fps": 16,
        "wan_duration": 5,
        "ltxv_steps": 30,
        "ltxv_cfg": 3.0,
        "ltxv_width": 768,
        "ltxv_height": 512,
        "ltxv_frames": 97,
        "ltxv_fps": 24,
    },
    "max": {
        "flux_steps": 40,
        "wan_steps": 28,
        "wan_split": 14,
        "wan_cfg": 4.0,
        "wan_width": 768,
        "wan_height": 768,
        "wan_fps": 16,
        "wan_duration": 5,
        "ltxv_steps": 40,
        "ltxv_cfg": 3.5,
        "ltxv_width": 960,
        "ltxv_height": 640,
        "ltxv_frames": 121,
        "ltxv_fps": 24,
    },
}


def quality_profile(value):
    return QUALITY_PROFILES.get(str(value or "balanced").lower(), QUALITY_PROFILES["balanced"])


def set_node_widget(node_data, index, value):
    widgets = node_data.setdefault("widgets_values", [])
    while len(widgets) <= index:
        widgets.append(None)
    widgets[index] = value


def patch_prompt_nodes(wf, positive, negative=None):
    for node_data in wf.get("nodes", []):
        if node_data.get("type") != "CLIPTextEncode":
            continue
        title = str(node_data.get("title") or "").lower()
        current = str((node_data.get("widgets_values") or [""])[0]).lower()
        is_negative = "negative" in title or current.startswith("low quality") or "worst quality" in current
        if is_negative:
            if negative:
                set_node_widget(node_data, 0, negative)
        else:
            set_node_widget(node_data, 0, positive)


def patch_save_video_nodes(wf, prefix):
    for node_data in wf.get("nodes", []):
        if node_data.get("type") == "SaveVideo":
            set_node_widget(node_data, 0, prefix)
            set_node_widget(node_data, 1, "mp4")
            set_node_widget(node_data, 2, "h264")


def patch_power_lora_node(node_data, slots):
    widgets = node_data.setdefault("widgets_values", [{}, {"type": "PowerLoraLoaderHeaderWidget"}])
    while len(widgets) < 7:
        widgets.append({})
    for index in range(3):
        if index < len(slots):
            widgets[index + 2] = {
                "on": True,
                "lora": slots[index]["name"],
                "strength": float(slots[index]["strength"]),
                "strengthTwo": None,
            }
        else:
            widgets[index + 2] = {"on": False, "lora": "None", "strength": 1, "strengthTwo": None}


def wan_branch_lora_slots(slots, branch):
    branch = branch.lower()
    out = []
    for slot in slots:
        name = slot["name"].lower()
        is_high = "high_noise" in name or "high-noise" in name or "highnoise" in name or "-high" in name or "_high" in name
        is_low = "low_noise" in name or "low-noise" in name or "lownoise" in name or "-low" in name or "_low" in name
        if branch == "high" and (is_high or not is_low):
            out.append(slot)
        elif branch == "low" and (is_low or not is_high):
            out.append(slot)
    return out


def video_template_candidates(recipe):
    if recipe == "wan_t2v":
        return "Wan", [
            TEMPLATE_DIR / "Wan/video_wan2_2_14B_t2v_flat.json",
            DESKTOP_WORKFLOWS / "Wan/video_wan2_2_14B_t2v_flat.json",
        ]
    if recipe == "ltxv_t2v":
        return "LTXV", [
            TEMPLATE_DIR / "LTXV/ltxv_13b_text_to_video_lora.json",
            DESKTOP_WORKFLOWS / "LTXV/LTXV 13B Text to Video with LoRA.json",
        ]
    raise ValueError(f"{recipe} is not a video recipe")


def load_video_template(recipe):
    family, candidates = video_template_candidates(recipe)
    for src in candidates:
        if src.exists():
            return json.loads(src.read_text(encoding="utf-8")), family, src
    checked = ", ".join(str(path) for path in candidates)
    raise FileNotFoundError(f"No {family} video template found. Checked: {checked}")


def patch_wan_template(wf, prompt, lora_slots, name, quality):
    profile = quality_profile(quality)
    patch_prompt_nodes(wf, prompt)
    patch_save_video_nodes(wf, "video/Assistant_Wan")
    for node_data in wf.get("nodes", []):
        ntype = node_data.get("type")
        title = str(node_data.get("title") or "")
        if ntype == "Power Lora Loader (rgthree)":
            branch = "high" if "high" in title.lower() else "low"
            patch_power_lora_node(node_data, wan_branch_lora_slots(lora_slots, branch)[:3])
        elif ntype == "PrimitiveBoolean" and "Lightning" in title:
            set_node_widget(node_data, 0, False)
        elif ntype == "PrimitiveInt" and "Steps" in title and "Split" not in title:
            set_node_widget(node_data, 0, profile["wan_steps"])
        elif ntype == "PrimitiveInt" and "Split" in title:
            set_node_widget(node_data, 0, profile["wan_split"])
        elif ntype == "PrimitiveFloat" and "CFG" in title:
            set_node_widget(node_data, 0, profile["wan_cfg"])
        elif ntype == "PrimitiveFloat" and "FPS" in title:
            set_node_widget(node_data, 0, profile["wan_fps"])
        elif ntype == "PrimitiveFloat" and "Duration" in title:
            set_node_widget(node_data, 0, profile["wan_duration"])
        elif ntype == "EmptyHunyuanLatentVideo":
            set_node_widget(node_data, 0, profile["wan_width"])
            set_node_widget(node_data, 1, profile["wan_height"])
    wf.setdefault("extra", {}).setdefault("assistant_builder", {})
    wf["extra"]["assistant_builder"].update(
        {"media_type": "video", "recipe": "wan_t2v", "prompt": prompt, "name": name, "quality": quality}
    )


def patch_ltxv_template(wf, prompt, lora_slots, name, quality):
    profile = quality_profile(quality)
    patch_prompt_nodes(wf, prompt)
    patch_save_video_nodes(wf, "video/Assistant_LTXV")
    for node_data in wf.get("nodes", []):
        ntype = node_data.get("type")
        if ntype == "LoraLoaderModelOnly":
            if lora_slots:
                set_node_widget(node_data, 0, lora_slots[0]["name"])
                set_node_widget(node_data, 1, float(lora_slots[0]["strength"]))
            else:
                set_node_widget(node_data, 1, 0.0)
        elif ntype == "EmptyLTXVLatentVideo":
            set_node_widget(node_data, 0, profile["ltxv_width"])
            set_node_widget(node_data, 1, profile["ltxv_height"])
            set_node_widget(node_data, 2, profile["ltxv_frames"])
        elif ntype == "LTXVScheduler":
            set_node_widget(node_data, 0, profile["ltxv_steps"])
        elif ntype == "SamplerCustom":
            set_node_widget(node_data, 3, profile["ltxv_cfg"])
        elif ntype == "CreateVideo":
            set_node_widget(node_data, 0, profile["ltxv_fps"])
        elif ntype == "LTXVConditioning":
            set_node_widget(node_data, 0, profile["ltxv_fps"])
    wf.setdefault("extra", {}).setdefault("assistant_builder", {})
    wf["extra"]["assistant_builder"].update(
        {"media_type": "video", "recipe": "ltxv_t2v", "prompt": prompt, "name": name, "quality": quality}
    )


def validate_workflow_model_files(wf):
    checks = {
        "UNETLoader": ("diffusion_models", 0),
        "CLIPLoader": ("text_encoders", 0),
        "VAELoader": ("vae", 0),
        "CheckpointLoaderSimple": ("checkpoints", 0),
        "LoraLoaderModelOnly": ("loras", 0),
    }
    missing = []
    for node_data in wf.get("nodes", []):
        ntype = node_data.get("type")
        if ntype not in checks:
            continue
        model_dir, widget_index = checks[ntype]
        widgets = node_data.get("widgets_values") or []
        if len(widgets) <= widget_index:
            continue
        model_name = str(widgets[widget_index] or "")
        if not model_name or model_name == "None":
            continue
        if ntype == "LoraLoaderModelOnly":
            strength = float(widgets[1] or 0) if len(widgets) > 1 else 1.0
            if strength == 0 or "lightx2v" in model_name.lower():
                continue
        path = MODEL_DIRS[model_dir] / model_name
        if not path.exists():
            missing.append(f"{ntype}: {model_dir}/{model_name}")
    for node_data in wf.get("nodes", []):
        if node_data.get("type") != "Power Lora Loader (rgthree)":
            continue
        for item in (node_data.get("widgets_values") or [])[2:5]:
            if not isinstance(item, dict) or not item.get("on"):
                continue
            model_name = str(item.get("lora") or "")
            if model_name and model_name != "None" and not (MODEL_DIRS["loras"] / model_name).exists():
                missing.append(f"Power LoRA: loras/{model_name}")
    if missing:
        raise FileNotFoundError("Missing required ComfyUI model files: " + "; ".join(missing))


def video_workflow(prompt, *, recipe, loras=None, name="Assistant Video", quality="balanced"):
    wf, family, src = load_video_template(recipe)
    lora_slots = normalize_lora_slots(prompt, loras, recipe=recipe)
    wf["id"] = slugify(name).lower().replace(" ", "-")
    if recipe == "wan_t2v":
        patch_wan_template(wf, prompt, lora_slots, name, quality)
    elif recipe == "ltxv_t2v":
        patch_ltxv_template(wf, prompt, lora_slots, name, quality)
    wf.setdefault("extra", {}).setdefault("assistant_builder", {})
    wf["extra"]["assistant_builder"]["template"] = str(src)
    validate_workflow_model_files(wf)
    return wf, family


def workflow(title, nodes, links, last_node_id, last_link_id, family):
    return (
        {
            "id": slugify(title).lower().replace(" ", "-"),
            "revision": 0,
            "last_node_id": last_node_id,
            "last_link_id": last_link_id,
            "nodes": nodes,
            "links": links,
            "groups": [
                {
                    "id": 1,
                    "title": "Model and adapters",
                    "bounding": [20, -25, 760, 190],
                    "color": "#3f789e",
                    "font_size": 24,
                    "flags": {},
                },
                {
                    "id": 2,
                    "title": "Prompt",
                    "bounding": [20, 175, 1230, 235],
                    "color": "#3f789e",
                    "font_size": 24,
                    "flags": {},
                },
                {
                    "id": 3,
                    "title": "Sample and save",
                    "bounding": [20, 425, 2220, 235],
                    "color": "#3f789e",
                    "font_size": 24,
                    "flags": {},
                },
            ],
            "config": {},
            "extra": {
                "ds": {"scale": 0.72, "offset": [130, 110]},
                "frontendVersion": "1.43.18",
                "assistant_builder": {"family": family, "created": int(time.time())},
            },
            "version": 0.4,
        },
        family,
    )


def build_workflow(payload):
    prompt = payload.get("prompt", "")
    recipe = payload.get("recipe") or infer_recipe(prompt)
    media_type = normalize_media_type(payload.get("media_type"), recipe)
    quality = str(payload.get("quality") or "balanced").lower()
    if media_type == "image" and recipe not in {"flux_lora", "flux_base"}:
        recipe = "flux_lora"
    elif media_type == "video" and recipe in {"flux_lora", "flux_base"}:
        recipe = "wan_t2v"
    name = slugify(payload.get("name") or f"Assistant {recipe} {int(time.time())}")
    if recipe == "flux_base":
        wf, family = flux_workflow(prompt, with_lora=False, title=name, quality=quality)
    elif recipe == "flux_lora":
        strength = float(payload.get("lora_strength") or 0.75)
        wf, family = flux_workflow(
            prompt,
            lora=payload.get("lora") or None,
            loras=payload.get("loras"),
            strength=strength,
            with_lora=True,
            title=name,
            quality=quality,
        )
    else:
        wf, family = video_workflow(
            prompt,
            recipe=recipe,
            loras=payload.get("loras"),
            name=name,
            quality=quality,
        )
    return wf, family, name


def save_workflow(wf, family, name):
    target_dir = DESKTOP_WORKFLOWS / family
    target_dir.mkdir(parents=True, exist_ok=True)
    path = target_dir / f"{name}.json"
    path.write_text(json.dumps(wf, indent=2), encoding="utf-8")

    COMFY_WORKFLOWS.mkdir(parents=True, exist_ok=True)
    link = COMFY_WORKFLOWS / path.name
    if link.exists() or link.is_symlink():
        if link.is_symlink() or link.resolve() == path:
            link.unlink()
        else:
            backup = link.with_suffix(link.suffix + f".backup-{int(time.time())}")
            link.rename(backup)
    link.symlink_to(path)
    return path, link


def comfy_status():
    try:
        with urlrequest.urlopen(f"{COMFY_API}/system_stats", timeout=3) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except Exception as exc:
        return {"error": str(exc)}


class Handler(BaseHTTPRequestHandler):
    server_version = "ComfyAssistantBuilder/0.1"

    def end_headers(self):
        origin = self.headers.get("Origin", "")
        if origin.startswith("chrome-extension://") or origin in {
            f"http://{HOST}:{PORT}",
            f"http://localhost:{PORT}",
            "http://127.0.0.1:8188",
            "http://localhost:8188",
        }:
            self.send_header("Access-Control-Allow-Origin", origin)
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, X-CAB-Token")
        self.send_header("X-Content-Type-Options", "nosniff")
        super().end_headers()

    def do_OPTIONS(self):
        self.send_response(204)
        self.end_headers()

    def do_GET(self):
        parsed = urlparse(self.path)
        if parsed.path == "/api/models":
            if not self.authorized():
                return self.json({"ok": False, "error": "unauthorized"}, code=401)
            return self.json(scan_models())
        if parsed.path == "/api/status":
            if not self.authorized():
                return self.json({"ok": False, "error": "unauthorized"}, code=401)
            return self.json({"ok": True, "comfy": comfy_status()})
        if parsed.path == "/api/lora-info":
            if not self.authorized():
                return self.json({"ok": False, "error": "unauthorized"}, code=401)
            name = parse_qs(parsed.query).get("name", [""])[0]
            return self.json(lora_info(name))
        if parsed.path == "/config.js":
            raw = f"window.CAB_TOKEN = {json.dumps(API_TOKEN)};\n".encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "application/javascript")
            self.send_header("Cache-Control", "no-store")
            self.send_header("Content-Length", str(len(raw)))
            self.end_headers()
            self.wfile.write(raw)
            return
        if parsed.path in ("/", "/index.html"):
            return self.file(STATIC_DIR / "index.html")
        path = STATIC_DIR / parsed.path.lstrip("/")
        if path.exists() and path.is_file():
            return self.file(path)
        self.send_error(404)

    def do_POST(self):
        parsed = urlparse(self.path)
        try:
            length = int(self.headers.get("Content-Length", "0"))
            payload = json.loads(self.rfile.read(length).decode("utf-8") or "{}")
            if parsed.path == "/api/build":
                if not self.authorized(payload):
                    return self.json({"ok": False, "error": "unauthorized"}, code=401)
                wf, family, name = build_workflow(payload)
                saved = None
                link = None
                if payload.get("save", True):
                    saved, link = save_workflow(wf, family, name)
                return self.json(
                    {
                        "ok": True,
                        "family": family,
                        "name": name,
                        "workflow": wf,
                        "saved_path": str(saved) if saved else None,
                        "comfy_link": str(link) if link else None,
                    }
                )
            self.send_error(404)
        except Exception as exc:
            self.json({"ok": False, "error": str(exc)}, code=500)

    def authorized(self, payload=None):
        header = self.headers.get("X-CAB-Token", "")
        return secrets.compare_digest(header, API_TOKEN)

    def json(self, data, code=200):
        raw = json.dumps(data, indent=2).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(raw)))
        self.end_headers()
        self.wfile.write(raw)

    def file(self, path: Path):
        raw = path.read_bytes()
        self.send_response(200)
        self.send_header("Content-Type", mimetypes.guess_type(str(path))[0] or "application/octet-stream")
        self.send_header("Content-Length", str(len(raw)))
        self.end_headers()
        self.wfile.write(raw)

    def log_message(self, fmt, *args):
        print(f"[{self.log_date_time_string()}] {fmt % args}")


def main():
    os.chdir(APP_DIR)
    write_extension_config()
    httpd = ThreadingHTTPServer((HOST, PORT), Handler)
    url = f"http://{HOST}:{PORT}"
    print(f"Comfy Assistant Builder running at {url}")
    print(f"ComfyUI API: {COMFY_API}")
    print(f"ComfyUI root: {COMFY_ROOT}")
    print(f"Workflow output folder: {DESKTOP_WORKFLOWS}")
    print(f"API token file: {TOKEN_PATH}")
    print(f"Chrome extension folder: {APP_DIR / 'chrome_extension'}")
    try:
        webbrowser.open(url)
    except Exception:
        pass
    httpd.serve_forever()


if __name__ == "__main__":
    main()
